### chat-with-rag (Exist in documents)
POST http://localhost:8080/rag?clientId=c_1
Content-Type: application/json

{
  "question": "What is the required approach for Software Engineering in Deep Learning Systems?"
}

### chat-with-rag (Not in documents)
POST http://localhost:8080/rag?clientId=c_1
Content-Type: application/json

{
  "question": "How Tesla Cars get built?"
}
