### chat-with-rag (Exist in documents)
POST http://localhost:8080/rag?clientId=c_1
Content-Type: application/json

{
  "question": "How AI engineering required to build reliable deep learning-based software systems"
}

### chat-with-rag (Not in documents)
POST http://localhost:8080/rag/report?clientId=client-a&conversationsId=1
Content-Type: application/json

{
  "question": "How Tesla Cars get built?"
}
